name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Replace Environment Variable in Code
        run: |
          find . -type f -name '*.js' -exec sed -i 's/\${process.env.REACT_APP_API_URL}/api/g' {} +
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify Node.js version, adjust as needed
      - name: Install Dependencies
        run: |
          cd frontend  # Change directory to frontend where package.json is located
          npm install
      - name: Build Project
        run: |
          cd frontend  # Ensure we are in the correct directory to build the project
          npm run build

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_POND_0313EC103 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend" # App source code path
          api_location: "backend" # Api source code path - optional!!!
          output_location: "build" # Built app content directory - optional

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_POND_0313EC103 }}
          action: "close"
